import os
import tempfile
import unittest
from datetime import date

from coalib.output.ConfWriter import ConfWriter
from coala_quickstart.generation.Settings import write_info

class SettingsTest(unittest.TestCase):

    def setUp(self):
        self.coafile = os.path.join(tempfile.gettempdir(), '.coafile')
        self.writer = ConfWriter(self.coafile)
        
    def tearDown(self):
        self.writer.close()
        os.remove(self.coafile)
        
    def test_write_info(self):
        result_date = date.today().strftime("%d %b %Y")
        result_comment = ('# Generated by coala-quickstart on '
                          '{date}.\n'.format(date=result_date))
        write_info(self.writer)
        self.writer.close()
        
        with open(self.coafile, 'r') as f:
            line = f.readline()
            
        self.assertEqual(result_comment, line)
